export const APIPath = {
  Invitation: {
    AcceptInvitation: '/Invitation/AcceptInvitation',
    DeclineInvitation: '/Invitation/DeclineInvitation',
    CreateInvitation: '/Invitation/CreateInvitation',
    SendInvitation: '/Invitation/SendInvitation',
    RevokeInvitation: '/Invitation/RevokeInvitation',
  },
  Message: {
    SendMessage: '/Message/SendMessage',
    UpdateMessage: '/Message/UpdateMessage',
    AddMessageReaction: '/Message/AddMessageReaction',
    RevokeMessageReaction: '/Message/RevokeMessageReaction',
    QuoteMessage: '/Message/QuoteMessage',
    ForwardMessagesToChannel: '/Message/ForwardMessagesToChannel',
    ReportMessage: '/Message/ReportMessage',
    MarkAsRead: '/Message/MarkAsRead',
    MarkDmAsRead: '/Message/MarkDMAsRead',
    SendMessageSticker: '/Message/SendMessageSticker',
    SendDmMessageSticker: '/Message/SendDMMessageSticker',
    MarkAllChannelsAsRead: '/Message/MarkAllChannelsAsRead',
    SendDMMessage: '/Message/SendDMMessage',
    SendDMMessageSticker: '/Message/SendDMMessageSticker',
    UpdateDMMessage: '/Message/UpdateDMMessage',
    AddDMMessageReaction: '/Message/AddDMMessageReaction',
    RevokeDMMessageReaction: '/Message/RevokeDMMessageReaction',
    QuoteDMMessage: '/Message/QuoteDMMessage',
    ForwardMessagesToDMChannel: '/Message/ForwardMessagesToDMChannel',
    ReportDMMessage: '/Message/ReportDMMessage',
    MarkDMAsRead: '/Message/MarkDMAsRead',
    Translation: '/Message/Translation',
    PinUnpinDmMessage: '/Message/PinUnpinDMMessage',
    PinUnpinMessage: '/Message/PinUnpinMessage',
    SendLocation: '/Message/SendLocation',
    SendDmLocation: '/Message/SendDMLocation',
    SendPokeMessage: '/Message/SendPokeMessage',
    SendDmMessageMedia: '/Message/SendDmMessageMedia',
    UpdateDmMediaAttachments: '/Message/UpdateDmMediaAttachments',
    UpdateMediaAttachments: '/Message/UpdateMediaAttachments',
    SendMessageMedia: '/Message/SendMessageMedia',
    DeleteDmMessagesOnlyMe: '/Message/DeleteDMMessagesOnlyMe',
    DeleteDmMessagesForEveryone: '/Message/DeleteDMMessageForEveryone',
    DeleteMessagesOnlyMe: '/Message/DeleteMessagesOnlyMe',
    DeleteMessagesForEveryone: '/Message/DeleteMessageForEveryone',
  },
  ViewChannel: {
    GetChannel: '/ChannelView/GetChannel',
    ListAllChannels: '/ChannelView/ListAllChannels',
    GetDMChannel: '/ChannelView/GetDMChannel',
    ListChannels: '/ChannelView/ListChannels',
    ListDMChannels: '/ChannelView/ListDMChannels',
    ListInComingMessageRequests: '/ChannelView/ListInComingMessageRequests',
    ListOutGoingMessageRequests: '/ChannelView/ListOutGoingMessageRequests',
    SyncAllChannels: '/ChannelView/SyncAllChannels',
  },
  ViewMessage: {
    GetMessage: '/MessageView/GetMessage',
    GetDMMessage: '/MessageView/GetDMMessage',
    ListMessages: '/MessageView/ListMessages',
    ListDMMessages: '/MessageView/ListDMMessages',
    JumpToDMMessage: '/MessageView/JumpToDMMessage',
    JumpToMessage: '/MessageView/JumpToMessage',
    ListDMMessageReaction: '/MessageView/ListDMMessageReactions',
    ListMessageReaction: '/MessageView/ListMessageReactions',
    GetPinnedMessage: '/MessageView/GetPinnedMessage',
    GetPinnedDMMessage: '/MessageView/GetPinnedDMMessage',
    ListMessagesFragment: '/MessageView/ListMessageFragments',
  },
  ViewUser: {
    GetUser: '/UserView/GetUser',
    GetUserByUsername: '/UserView/GetUserByUsername',
    GetMe: '/UserView/GetMe',
    SyncUsers: '/UserView/SyncUsers',
    ListBlockedUsers: '/UserView/ListBlockedUsers',
  },
  ViewFriend: {
    ListFriend: '/FriendView/ListFriends',
    GetFriend: '/FriendView/GetFriend',
    ListInComingFriendRequests: '/FriendView/ListInComingFriendRequests',
    ListOutGoingFriendRequests: '/FriendView/ListOutGoingFriendRequests'
  },
  ViewInvitation: {
    ListInvitation: '/InvitationView/ListInvitation',
    GetInvitation: '/InvitationView/GetInvitation',
  },
  Channel: {
    CreateChannel: '/Channel/CreateChannel',
    UpdateChannelName: '/Channel/UpdateChannelName',
    UpdateChannelAvatar: '/Channel/UpdateChannelAvatar',
    UpdateDMMediaPermissionSetting: '/Channel/UpdateDMMediaPermissionSetting',
    AcceptMessageRequest: '/Channel/AcceptMessageRequest',
    RejectMessageRequest: '/Channel/RejectMessageRequest',
    DeleteChannel: '/Channel/DeleteChannel',
    DeleteChannelAvatar: '/Channel/DeleteChannelAvatar',
  },
  Search: {
    SearchChannels: '/Search/SearchChannels',
    SearchFriends: '/Search/SearchFriends',
    SearchUsers: '/Search/SearchUsers',
    SearchMembers: '/Search/SearchMembers',
  },
  ViewSticker: {
    GetSticker: '/StickerView/GetSticker',
    ListAllStickerCollections: '/StickerView/ListAllStickerCollections',
    GetStickerCollection: '/StickerView/GetStickerCollection',
    ListStickers: '/StickerView/ListStickers',
    SyncStickerCollections: '/StickerView/SyncStickerCollections',
  },
  Faker: {
    MockedUsers: '/InternalFaker/MockUsers',
    DeleteMockedUsers: '/InternalFaker/DeleteMockedUsers',
  },
  Friend: {
    AddFriend: '/Friend/AddFriend',
    Unfriend: '/Friend/Unfriend',
    RemoveFriend: '/Friend/RemoveFriend',
    BlockUser: '/Friend/BlockUser',
    UnblockUser: '/Friend/UnblockUser',
    AcceptFriendRequest: '/Friend/AcceptFriendRequest',
    RejectFriendRequest: '/Friend/RejectFriendRequest',
    CancelFriendRequest: '/Friend/CancelFriendRequest',
    DeleteFriendRequest: '/Friend/DeleteFriendRequest',
  },
  UserProfile: {
    UpdateUserDisplayName: '/UserProfile/UpdateUserDisplayName',
    AddUserStatus: '/UserProfile/AddUserStatus',
    UpdateUserStatus: '/UserProfile/UpdateUserStatus',
    DeleteUserVisitProfile: '/UserProfile/DeleteUserVisitedProfile',
    VisitProfile: '/UserProfile/VisitedProfile',
    AddCoverPhoto: '/UserProfile/AddCoverPhoto',
    UpdateCoverPhoto: '/UserProfile/UpdateCoverPhoto',
    AvatarFramePath: '/AvatarFrame/CreateAvatarFrame',
    DeleteAvatarFrame: '/AvatarFrame/DeleteAvatarFrame',
    DeleteUserAvatar: '/UserProfile/DeleteUserAvatar',
    UpdateUserEmail: '/UserProfile/UpdateUserEmail',
    UpdateUserAvatar: 'UserProfile/UpdateUserAvatar'
  },
  ViewMember: {
    ListMembers: '/MemberView/ListMembers',
    GetMember: '/MemberView/GetMember',
    ListBannedUser: 'Member/ListBannedUsers'
  },
  UserReport: {
    ReportUser: '/UserReport/ReportUser',
  },
  Member: {
    UpdateNickname: '/Member/UpdateNickname',
    AssignAsAdmin: '/Member/AssignAsAdmin',
    DismissAsAdmin: '/Member/DismissAsAdmin',
    BanFromChannel: '/Member/BanFromChannel',
    UnbanFromChannel: '/Member/UnbanFromChannel',
    TransferOwnership: '/Member/TransferOwnership',
    TransferOwnershipAndLeaveChannel:
      '/Member/TransferOwnershipAndLeaveChannel',
    LeaveChannel: '/Member/LeaveChannel',
    RemoveFromChannel: '/Member/RemoveFromChannel',
  },
  UserSetting: {
    BlockUser: '/UserSetting/BlockUser',
    UnBlockUser: '/UserSetting/UnblockUser'
  },
  RingBackTone: {
    RingBackToneCreate: '/RingbackTone/RingbackToneCreate',
    RingBackToneRename: '/RingbackTone/RingbackToneRename',
    SetRingBackTone: '/RingbackTone/SetRingbackTone',
  }
};
